### ISSUE TITLE
ng g component not working

### ISSUE THREAD

**Issue by Lokendra2500** [creativetimofficial/material-dashboard-pro-angular#158]
When i generate a new component by using "ng g component my-component-name", it was give an error
input.mergeMap is not a function
TypeError: input.mergeMap is not a function
    at Object.callRule (E:\Personal\codesslab\VMS-material\VMS\node_modules\@angular-devkit\schematics\src\rules\call.js:78:18)
    at SchematicImpl.call (E:\Personal\codesslab\VMS-material\VMS\node_modules\@angular-devkit\schematics\src\engine\schematic.js:35:23)
    at Promise (E:\Personal\codesslab\VMS-material\VMS\node_modules\@angular\cli\tasks\schematic-run.js:77:23)
    at Class.run (E:\Personal\codesslab\VMS-material\VMS\node_modules\@angular\cli\tasks\schematic-run.js:76:16)
    at Class.run (E:\Personal\codesslab\VMS-material\VMS\node_modules\@angular\cli\commands\generate.js:138:33)
    at resolve (E:\Personal\codesslab\VMS-material\VMS\node_modules\@angular\cli\ember-cli\lib\models\command.js:273:20)
    at Class.validateAndRun (E:\Personal\codesslab\VMS-material\VMS\node_modules\@angular\cli\ember-cli\lib\models\command.js:251:12)
    at Promise.resolve.then.then (E:\Personal\codesslab\VMS-material\VMS\node_modules\@angular\cli\ember-cli\lib\cli\cli.js:154:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)

anybody help me..

**Comment by bommen** [comment]
Same issue here

**Comment by Lokendra2500** [comment]
Hii @bommen ;

Then how you work on this theme... how you create any component, module and other things..

**Comment by gamalaraouf** [comment]
Same issue here

**Comment by chelaruc** [comment]
@Lokendra2500 @bommen @gamalaraouf Can you send me an archive for testing here: ciprian@creative-tim.com? I've tested in our project and everything is working good.

**Comment by bommen** [comment]
Hello @chelaruc ,

It happened when I updated the project to Angular 5 + Angular CLI 1.6.0. I think the CLI-version was the culprit. When I downgraded the version to 1.5.0 it worked again. Thanks anyway for your answer!

Bart
