### ISSUE TITLE
Index opens as white page

### ISSUE THREAD

**Issue by skullomania** [creativetimofficial/material-dashboard-pro-angular#39]
Following the steps on the readme I can only get through the first step of the installation. I am using windows 7

The "@angular/compiler-cli" package was not properly installed. Error: Error: Ca
nnot find module '@angular/compiler-cli'
Error: The "@angular/compiler-cli" package was not properly installed. Error: Er
ror: Cannot find module '@angular/compiler-cli'
    at Object.<anonymous> (C:\node_modules\@ngtools\webpack\src\index.js:14:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\node_modules\@angular\cli\tasks\eject.js:10:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by alexandru-paduraru** [comment]
@skullomania as we discussed on email and other comments you said that you found a way to work so I will close this issue.
