### ISSUE TITLE
md-checkbox

### ISSUE THREAD

**Issue by karthinuk107** [creativetimofficial/material-dashboard-pro-angular#4]
Uncaught ReferenceError: noUiSlider is not defined
    at material-dashboard-angular.js:122
jquery-3.1.1.min.js:2 jQuery.Deferred exception: md is not defined ReferenceError: md is not defined
    at HTMLDocument.<anonymous> (http://localhost:3000/assets/js/material-dashboard-angular.js:40:5)
    at j (http://localhost:3000/assets/js/core/jquery-3.1.1.min.js:2:29948)
    at k (http://localhost:3000/assets/js/core/jquery-3.1.1.min.js:2:30262)
    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:275:35)
    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:151:47)
    at ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:345:33)
    at data.args.(anonymous function) (http://localhost:3000/node_modules/zone.js/dist/zone.js:1298:25) undefined
r.Deferred.exceptionHook @ jquery-3.1.1.min.js:2
zone.js:155 Uncaught ReferenceError: md is not defined
    at HTMLDocument.<anonymous> (http://localhost:3000/assets/js/material-dashboard-angular.js:40:5)
    at j (http://localhost:3000/assets/js/core/jquery-3.1.1.min.js:2:29948)
    at k (http://localhost:3000/assets/js/core/jquery-3.1.1.min.js:2:30262)
    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:275:35)
    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:151:47)
    at ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:345:33)
    at data.args.(anonymous function) (http://localhost:3000/node_modules/zone.js/dist/zone.js:1298:25)
zone.js:420 Unhandled Promise rejection: Cannot set property 'stack' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot set property 'stack' of undefined
    at SyntaxError.set [as stack] (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:1630:65)
    at assignAll (http://localhost:3000/node_modules/zone.js/dist/zone.js:704:29)
    at SyntaxError.ZoneAwareError (http://localhost:3000/node_modules/zone.js/dist/zone.js:775:16)
    at SyntaxError.BaseError [as constructor] (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:1592:20)
    at new SyntaxError (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:1795:20)
    at TemplateParser.parse (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:11435:23)
    at JitCompiler._compileTemplate (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:27548:72)
    at eval (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:27431:66)
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:27431:23)
    at createResult (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:27313:23)
    at ZoneDelegate.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:242:26)
    at Zone.run (http://localhost:3000/node_modules/zone.js/dist/zone.js:113:43)
    at http://localhost:3000/node_modules/zone.js/dist/zone.js:535:57
    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:275:35) TypeError: Cannot set property 'stack' of undefined
    at SyntaxError.set [as stack] (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:1630:65)
    at assignAll (http://localhost:3000/node_modules/zone.js/dist/zone.js:704:29)
    at SyntaxError.ZoneAwareError (http://localhost:3000/node_modules/zone.js/dist/zone.js:775:16)
    at SyntaxError.BaseError [as constructor] (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:1592:20)
    at new SyntaxError (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:1795:20)
    at TemplateParser.parse (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:11435:23)
    at JitCompiler._compileTemplate (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:27548:72)
    at eval (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:27431:66)
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:27431:23)
    at createResult (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:27313:23)
    at ZoneDelegate.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:242:26)
    at Zone.run (http://localhost:3000/node_modules/zone.js/dist/zone.js:113:43)
    at http://localhost:3000/node_modules/zone.js/dist/zone.js:535:57
    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:275:35)
consoleError @ zone.js:420
zone.js:422 ZoneAwareError

**Comment by chelaruc** [comment]
Hi @karthinuk107! I just fixed the issue and what you have to do is to go in `md-pro-angular2/app/dashboard/forms/extendedforms/extendedforms.component.ts` and delete line 30:
```
initSliders();
```

Keep in touch,
Ciprian
